version: '2'

services:
  nginx:
    build: ./nginx
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
    ports:
      - "80:80"

  django:
    build:
      context: .
      args:
        https_proxy: "${https_proxy}"
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    privileged: true
