version: '2'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./esper:/usr/src/app
    depends_on:
      - esper
    ports:
      - "80:80"

  esper:
    build:
      context: ./esper
      args:
        https_proxy: "${https_proxy}"
    volumes:
      - ./esper:/usr/src/app
    expose:
      - "8000"
