apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: archive-download
spec:
  replicas: 50
  template:
    metadata:
      labels:
        app: archive-download
    spec:
      containers:
        - name: archive-download
          image: gcr.io/visualdb-1046/archive-download
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1.1
