# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
