# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='in_commercial',
        ),
        migrations.AlterField(
            model_name='frame',
            name='shot_boundary',
            field=models.BooleanField(default=False),
        ),
    ]
