# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20181116_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='brightness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='contrast',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='sharpness',
            field=models.FloatField(null=True),
        ),
    ]
