# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20181210_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='shot_scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='query.ShotScale'),
        ),
    ]
