# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(to='query.Genre'),
        ),
    ]
