# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0012_auto_20181215_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='directors',
            field=models.ManyToManyField(to='query.Director'),
        ),
    ]
