# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0013_auto_20181215_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='box_office',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
