# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0014_auto_20181215_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cinematographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='cinematographers',
            field=models.ManyToManyField(to='query.Cinematographer'),
        ),
        migrations.AddField(
            model_name='video',
            name='editors',
            field=models.ManyToManyField(to='query.Editor'),
        ),
        migrations.AddField(
            model_name='video',
            name='producers',
            field=models.ManyToManyField(to='query.Producer'),
        ),
        migrations.AddField(
            model_name='video',
            name='writers',
            field=models.ManyToManyField(to='query.Writer'),
        ),
    ]
