# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0016_auto_20181215_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='budget_currency',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ratingCount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='release_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='release_month',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='countries',
            field=models.ManyToManyField(to='query.Country'),
        ),
        migrations.AddField(
            model_name='video',
            name='languages',
            field=models.ManyToManyField(to='query.Language'),
        ),
    ]
