# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_auto_20181216_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='decode_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='small_dataset',
            field=models.BooleanField(default=False),
        ),
    ]
