# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0018_auto_20181217_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Actor')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Character')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Video')),
            ],
        ),
    ]
