# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0021_posemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='saturation',
            field=models.FloatField(null=True),
        ),
    ]
