# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0022_frame_saturation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Actor', unique=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Gender')),
            ],
        ),
    ]
