# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0023_actorgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.ObjectLabel'),
        ),
    ]
