# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0024_auto_20190108_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='labeler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='query.Labeler'),
            preserve_default=False,
        ),
    ]
