# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0027_frame_regularly_sampled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='cinematic',
            field=models.BooleanField(default=False),
        ),
    ]
