# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0029_video_ignore_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='transition_in_max_frame',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='transition_out_min_frame',
            field=models.IntegerField(null=True),
        ),
    ]
